<a href="https://colab.research.google.com/github/nicolesarnaglia-debug/DataScience/blob/main/ciencia_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
cidades = pd.Dataframe(
[
    ["Paraná", "Londrina", 575377, 1356.00],
    ["São Paulo", "São Carlos", 254484, 1508.00],
    ["Santa Catarina", "Florianópolis", 508826, 1798.00],
    ["Paraná","Curitiba", 1963726, 2293.00],
    ["São Paulo", "Campinas", 1223237, 1710.00]
], columns=["Estado", "Cidade", "Habitantes", "Salário-Médio"])
cidades

AttributeError: module 'pandas' has no attribute 'Dataframe'

In [9]:
df = pd.read_csv('qualidade_vinho.csv', sep= ',', header=0)

df.head(2)

FileNotFoundError: [Errno 2] No such file or directory: 'qualidade_vinho.csv'

In [5]:
cidades.head(2) # Retorna um novo dataframe com as n primeiras amostras

NameError: name 'cidades' is not defined

In [10]:
cidades.tail(2) # Retorna um novo dataframe com as n últimas amostras

NameError: name 'cidades' is not defined

In [ ]:
cidades.tail(2) # Retorna um novo dataframe com as n últimas amostras

In [ ]:
cidades.info() # Retorna vazio e imprime na tela as informações gerais do

↪ dataframe

In [ ]:
cidades.columns # Retorna uma lista com o nome de todas as colunas

In [ ]:
cidades['Salário-Médio'].describe() # Retorna um objeto DataFrame com as

↪ medidas estatísticas para cada coluna

In [ ]:
cidades.dtypes

cidades.info()

In [ ]:
cidades['Habitantes'] = cidades['Habitantes'].astype('float64')

cidades.dtypes

In [ ]:
cidades['Data'] = ['3-8-2021', '3-9-2021', '3-10-2021', '3-11-2021',

↪'3-12-2021']

cidades['Data'] = pd.to_datetime(cidades['Data'], format='%d-%m-%Y') #

↪ Dia, Mês, Ano

cidades

In [ ]:
cidades['Data'] = cidades['Data'].dt.strftime('%d-%m-%Y') # Dia, Mês, Ano

cidades # Novo Formato

In [ ]:
cidades.rename(columns={'Habitantes': 'N Habitantes', 'Data': 'Data -

↪ Censo'}, inplace=True)

cidades

In [ ]:
cidadesHab = cidades[['N Habitantes', 'Salário-Médio']] # Seleciona as

↪ duas colunas com os nomes especificados

cidadesHab

In [ ]:
cidades.loc[[1, 2]] # Seleciona as duas linhas com os nomes especificados

↪ (note que o "rótulo" de cada linha está presente na forma de números

↪ inteiros)

In [11]:
cidades_salarios = pd.DataFrame(

[

['Paraná', 'Londrina', 1356.00],

['São Paulo', 'São Carlos', 1508.00],

['Santa Catarina', 'Florianópolis', 1798.00],

['Paraná', 'Curitiba', 2293.00],

['São Paulo', 'Campinas', 1710.00]

], columns=['Estado', 'Cidade', 'Salário-Médio'])

cidades_salarios

           Estado         Cidade  Salário-Médio
0          Paraná       Londrina         1356.0
1       São Paulo     São Carlos         1508.0
2  Santa Catarina  Florianópolis         1798.0
3          Paraná       Curitiba         2293.0
4       São Paulo       Campinas         1710.0

In [12]:
cidades_pop = pd.DataFrame(

[

['Londrina', 575377],

['São Carlos', 254484],

['Florianópolis', 508826],

['Curitiba', 1963726],

['Campinas', 1223237]

], columns=['Cidade', 'Habitantes'])

cidades_pop

          Cidade  Habitantes
0       Londrina      575377
1     São Carlos      254484
2  Florianópolis      508826
3       Curitiba     1963726
4       Campinas     1223237